### ISSUE TITLE
extremely high windows sample rates confuse some of the players.

### ISSUE THREAD

**Issue by zaphod77** [mmontag/chip-player-js#150]
specifically anything higher than 96Khz breaks a lot of them. libadlmidi copes beautifully with it, but libfluidsynthlite chokes, and writes 96k samples anyway, resulting in wrong octaves.

My new computer can and does do 192khz 24 bit. it horribly breaks the vgm player as well.

**Comment by mmontag** [comment]
Thank you for pinpointing the issue here. Just when I thought I had fixed the sample rate issues, a new edge case appears...

In order to fix this, I might try to cap the AudioContext at 96 kHz. I don't imagine FluidSynth would benefit much from high sample rates because Soundfonts are authored at 44.1 kHz. The synth will just be doing a whole lot of interpolation.[^1]

[^1]: In my opinion, super high sample rates are mostly beneficial to the production process. It would be useful to record a tambourine sample at 192 kHz if you intend to [pitch it down 3 octaves](https://www.youtube.com/watch?v=Q4JvthGCtLM), because you'll retain high frequency information.

**Comment by zaphod77** [comment]
a higher sample rate might affect the sound of chorus some, at least in theory, but anyway i'm glad to find the case for you.
